# Generated by Django 3.2.16 on 2022-11-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('position', models.CharField(choices=[('fe', 'FrontEnd Software Developer'), ('be', 'Backend Software Developer'), ('manager', 'Project Manager'), ('ceo', 'Chief Executive Officer'), ('cto', 'Chief Technical Officer')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
