# Generated by Django 3.2.16 on 2022-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='docs',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pimage',
            field=models.ImageField(blank=True, upload_to='pimages'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('Gujarat', 'Gujarat'), ('Delhi', 'Delhi'), ('Uttar Pardesh', 'Uttar Pardesh'), ('Bihar', 'Bihar'), ('West Bangal', 'West Bangal'), ('Jharkhand', 'Jharkhand')], max_length=50, null=True),
        ),
    ]
